### ISSUE TITLE
Possible bug in EUTelDUTHistograms

### ISSUE THREAD

**Issue by tbisanz** [eutelescope/eutelescope#70]
When I try to run this processor on results I obtained via the new processors I get following exception:

```
 ***********************************************
 A runtime error occured - (uncaught exception):
      map::at
 Marlin will have to be terminated, sorry.
 ***********************************************
```

Setting a catchpoint reveals:
```
Catchpoint 1 (exception thrown), 0x0000003fd5cbccb0 in __cxa_throw () from /usr/lib64/libstdc++.so.6
#0  0x0000003fd5cbccb0 in __cxa_throw () from /usr/lib64/libstdc++.so.6
#1  0x0000003fd5c61db7 in std::__throw_out_of_range(char const*) () from /usr/lib64/libstdc++.so.6
#2  0x00007ffff1d5ae84 in at (this=0xa27270, event=<value optimized out>) at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_map.h:468
#3  eutelescope::EUTelDUTHistograms::processEvent (this=0xa27270, event=<value optimized out>) at /data-disk4/tbisanz/sw/ilcsoft/v01-17-05/Eutelescope/trunk/src/EUTelDUTHistograms.cc:685
#4  0x00007ffff67d644d in marlin::ProcessorMgr::processEvent(EVENT::LCEvent*) () from /data-disk4/tbisanz/sw/ilcsoft/v01-17-05/Marlin/v01-05/lib/libMarlin.so.1.5
#5  0x00007ffff7dcca9e in SIO::SIOReader::readStream(int) () from /data-disk4/tbisanz/sw/ilcsoft/v01-17-05/lcio/v02-04-03/lib/liblcio.so.2.4
#6  0x0000000000408c8e in main ()
```

Commenting out this one line will lead to other places where similar/equal out of range exceptions will be thrown. There is something not working out here. 
By the way, map::at is a C++11 feature, I'm not sure if non C++11 compliant compilers gurantee behaviour as stated by the standard, but to be honest I'm relatively sure that this is not causing the problem! It also works out fine for the old datura-noDUT example.

**Comment by tbisanz** [comment]
Fixed
